steps:
  # 1. Builds the image using the Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:${SHORT_SHA}', '.']

  # 2. Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:${SHORT_SHA}']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy classify-tumor \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app:${SHORT_SHA} \
          --region ${_REGION} \
          --allow-unauthenticated \
          --memory 2Gi \
          --add-cloudsql-instances=${PROJECT_ID}:${_REGION}:tumor-db \
          --set-env-vars="MODEL_BUCKET_NAME=${_BUCKET_NAME},MODEL_FILENAME=${_FILE_NAME}" \
          --set-env-vars="DATABASE_URL=postgresql://postgres:$$DB_PASS@/predictions?host=/cloudsql/${PROJECT_ID}:${_REGION}:tumor-db"
    secretEnv: ['DB_PASS']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest
    env: 'DB_PASS'

options:
  logging: CLOUD_LOGGING_ONLY