[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "classify_tumor"
authors = [
    { name="Olivia", email="olivia28c@gmail.com" }
]
version = "0.1.0"
description = "Simple CLI for tumor classification"
requires-python = ">=3.10"
dependencies = [
    "torch",
    "torchvision",
    "Pillow"
]

[project.optional-dependencies]
dev = ["pytest", "mypy"]

[project.scripts]
classify_tumor = "classify_tumor.cli:main"

[tool.setuptools.package-data]
"classify_tumor" = ["resources/*.pth"]

